namespace MagDbPatcher.ViewModels;

public sealed record VersionChainSegment(string Text, bool IsArrow);

public sealed class VersionDisplayItem
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public string? UpgradesTo { get; init; }
    public int ScriptCount { get; init; }

    public string Display =>
        $"{Id}  ({ScriptCount} script{(ScriptCount == 1 ? "" : "s")})  ->  {(string.IsNullOrWhiteSpace(UpgradesTo) ? "Latest" : UpgradesTo)}";
}

public sealed class PatchDisplayItem
{
    public string From { get; init; } = "";
    public string To { get; init; } = "";
    public int ScriptCount { get; init; }
    public bool IsAutoGenerated { get; init; }

    public string Display =>
        $"{From}  ->  {To}  ({ScriptCount} script{(ScriptCount == 1 ? "" : "s")}){(IsAutoGenerated ? "  AUTO" : "")}";
}

public sealed class StagedPatchLinkDisplay
{
    public string From { get; init; } = "";
    public string To { get; init; } = "";
    public int ScriptCount { get; init; }
    public bool Manual { get; init; }

    public string Display =>
        $"{From}  ->  {To}  ({ScriptCount} script{(ScriptCount == 1 ? "" : "s")}){(Manual ? "  MANUAL" : "  AUTO")}";
}
