using MagDbPatcher.Services;
using Xunit;

namespace MagDbPatcher.Tests;

public class PatcherConfigTests
{
    [Fact]
    public async Task StableToBuildSameMajor_GeneratesPatchesForAnyMajor()
    {
        var root = CreateTempDir();
        try
        {
            var patches = Path.Combine(root, "patches");
            Directory.CreateDirectory(patches);

            await File.WriteAllTextAsync(Path.Combine(patches, "versions.json"), """{ "versions": [], "patches": [] }""");
            await File.WriteAllTextAsync(Path.Combine(patches, "patcher.config.json"), """
            {
              "schemaVersion": 1,
              "versionOrdering": { "mode": "semantic_with_optional_buildDate" },
              "autoGenerate": {
                "buildVersionPattern": "-",
                "rules": [ { "type": "stable_to_build_same_major" } ]
              }
            }
            """);

            Directory.CreateDirectory(Path.Combine(patches, "8.0"));
            Directory.CreateDirectory(Path.Combine(patches, "8.1.0-20260201"));
            await File.WriteAllTextAsync(Path.Combine(patches, "8.1.0-20260201", "a.sql"), "SELECT 1;");

            var svc = new VersionService(patches);
            await svc.LoadVersionsAsync();

            Assert.False(svc.LastValidationResult.HasErrors);

            var patch = svc.GetAllPatches().FirstOrDefault(p => p.From == "8.0" && p.To == "8.1.0-20260201");
            Assert.NotNull(patch);
            Assert.True(patch!.AutoGenerated);
            Assert.Contains("8.1.0-20260201/a.sql", patch.Scripts);
        }
        finally
        {
            TryDelete(root);
        }
    }

    [Fact]
    public async Task FromVersionsToBuildMajor_GeneratesConfiguredDirectJumps()
    {
        var root = CreateTempDir();
        try
        {
            var patches = Path.Combine(root, "patches");
            Directory.CreateDirectory(patches);

            await File.WriteAllTextAsync(Path.Combine(patches, "versions.json"), """{ "versions": [], "patches": [] }""");
            await File.WriteAllTextAsync(Path.Combine(patches, "patcher.config.json"), """
            {
              "schemaVersion": 1,
              "versionOrdering": { "mode": "semantic_with_optional_buildDate" },
              "autoGenerate": {
                "buildVersionPattern": "-",
                "rules": [
                  { "type": "from_versions_to_build_major", "from": ["6.5"], "toMajor": 7 }
                ]
              }
            }
            """);

            Directory.CreateDirectory(Path.Combine(patches, "6.5"));
            Directory.CreateDirectory(Path.Combine(patches, "7.2.3-20260201"));
            await File.WriteAllTextAsync(Path.Combine(patches, "7.2.3-20260201", "patch.sql"), "SELECT 1;");

            var svc = new VersionService(patches);
            await svc.LoadVersionsAsync();

            Assert.False(svc.LastValidationResult.HasErrors);

            var patch = svc.GetAllPatches().FirstOrDefault(p => p.From == "6.5" && p.To == "7.2.3-20260201");
            Assert.NotNull(patch);
            Assert.True(patch!.AutoGenerated);
            Assert.Contains("7.2.3-20260201/patch.sql", patch.Scripts);
        }
        finally
        {
            TryDelete(root);
        }
    }

    [Fact]
    public async Task VersionOrdering_SortsStableBeforeBuildForSameSemver()
    {
        var root = CreateTempDir();
        try
        {
            var patches = Path.Combine(root, "patches");
            Directory.CreateDirectory(patches);

            await File.WriteAllTextAsync(Path.Combine(patches, "versions.json"), """{ "versions": [], "patches": [] }""");
            await File.WriteAllTextAsync(Path.Combine(patches, "patcher.config.json"), """
            {
              "schemaVersion": 1,
              "versionOrdering": { "mode": "semantic_with_optional_buildDate" },
              "autoGenerate": {
                "buildVersionPattern": "-",
                "rules": [ { "type": "stable_to_build_same_major" } ]
              }
            }
            """);

            Directory.CreateDirectory(Path.Combine(patches, "7.2.3"));
            Directory.CreateDirectory(Path.Combine(patches, "7.2.3-20260123"));
            await File.WriteAllTextAsync(Path.Combine(patches, "7.2.3-20260123", "a.sql"), "SELECT 1;");

            var svc = new VersionService(patches);
            await svc.LoadVersionsAsync();

            var versions = svc.GetAllVersions().Select(v => v.Id).ToList();
            var idxStable = versions.IndexOf("7.2.3");
            var idxBuild = versions.IndexOf("7.2.3-20260123");

            Assert.True(idxStable >= 0);
            Assert.True(idxBuild >= 0);
            Assert.True(idxStable < idxBuild);

            var patch = svc.GetAllPatches().FirstOrDefault(p => p.From == "7.2.3" && p.To == "7.2.3-20260123");
            Assert.NotNull(patch);
            Assert.True(patch!.AutoGenerated);
        }
        finally
        {
            TryDelete(root);
        }
    }

    private static string CreateTempDir()
    {
        var dir = Path.Combine(Path.GetTempPath(), "MagDbPatcherTests_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        return dir;
    }

    private static void TryDelete(string path)
    {
        try
        {
            if (Directory.Exists(path))
                Directory.Delete(path, recursive: true);
        }
        catch
        {
        }
    }
}

