using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using MagDbPatcher.Infrastructure;
using MagDbPatcher.Models;
using MagDbPatcher.Services;
using MagDbPatcher.ViewModels;
using Microsoft.Win32;

namespace MagDbPatcher;

public partial class AdminWindow : Window
{
    private VersionService _versionService;
    private readonly Func<Task>? _onDataChanged;
    private readonly Func<string> _getCurrentPatchesFolder;
    private readonly Func<string, Task>? _setPatchesFolderAsync;
    private readonly Func<Task<string>>? _resetPatchesFolderAsync;
    private readonly Func<Task>? _persistSettingsAsync;
    private readonly Func<VersionService?>? _getVersionService;

    private readonly IPatchCatalogService _catalogService = new PatchCatalogService();
    private readonly AdminUiStateController _uiStateController = new();

    private readonly ObservableCollection<VersionDisplayItem> _versions = new();
    private readonly ObservableCollection<PatchDisplayItem> _patches = new();
    private readonly ObservableCollection<string> _scriptsForVersion = new();
    private readonly ObservableCollection<string> _scriptsForPatch = new();
    private readonly ObservableCollection<VersionDisplayItem> _libraryVersions = new();
    private readonly ObservableCollection<string> _libraryScripts = new();
    private readonly ObservableCollection<StagedPatchLinkDisplay> _stagedLinks = new();

    private readonly List<PatchLinkMutation> _stagedLinkMutations = new();
    private PatchCatalogSnapshot? _librarySnapshot;
    private bool _isRefreshing;

    public AdminWindow(
        VersionService versionService,
        Func<Task>? onDataChanged = null,
        Func<string>? getCurrentPatchesFolder = null,
        Func<string, Task>? setPatchesFolderAsync = null,
        Func<Task<string>>? resetPatchesFolderAsync = null,
        Func<Task>? persistSettingsAsync = null,
        Func<VersionService?>? getVersionService = null)
    {
        _versionService = versionService;
        _onDataChanged = onDataChanged;
        _getCurrentPatchesFolder = getCurrentPatchesFolder ?? (() => versionService.GetPatchesFolder());
        _setPatchesFolderAsync = setPatchesFolderAsync;
        _resetPatchesFolderAsync = resetPatchesFolderAsync;
        _persistSettingsAsync = persistSettingsAsync;
        _getVersionService = getVersionService;

        InitializeComponent();

        lstVersions.ItemsSource = _versions;
        lstPatches.ItemsSource = _patches;
        lstScripts.ItemsSource = _scriptsForVersion;
        lstPatchScripts.ItemsSource = _scriptsForPatch;
        lstLibraryVersions.ItemsSource = _libraryVersions;
        lstLibraryScripts.ItemsSource = _libraryScripts;
        lstLibraryLinks.ItemsSource = _stagedLinks;

        Loaded += AdminWindow_Loaded;
    }

    private async void AdminWindow_Loaded(object sender, RoutedEventArgs e)
    {
        txtActivePatchesFolder.Text = _getCurrentPatchesFolder();
        await RefreshAdminDataAsync();
        await ScanCatalogAsync();
    }

    public async Task RefreshAdminDataAsync()
    {
        if (_isRefreshing)
            return;

        _isRefreshing = true;
        try
        {
            await _versionService.LoadVersionsAsync();

            var allVersions = _versionService.GetAllVersions();
            var allPatches = _versionService.GetAllPatches();

            var selectedVersionId = (lstVersions.SelectedItem as VersionDisplayItem)?.Id;
            var selectedPatchKey = GetSelectedPatchKey();

            _versions.Clear();
            foreach (var version in allVersions)
            {
                _versions.Add(new VersionDisplayItem
                {
                    Id = version.Id,
                    Name = version.Name,
                    UpgradesTo = version.UpgradesTo,
                    ScriptCount = _versionService.GetScriptCount(version.Id)
                });
            }

            _patches.Clear();
            foreach (var patch in allPatches
                         .OrderBy(p => p.From, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(p => p.To, StringComparer.OrdinalIgnoreCase))
            {
                _patches.Add(new PatchDisplayItem
                {
                    From = patch.From,
                    To = patch.To,
                    ScriptCount = patch.Scripts.Count,
                    IsAutoGenerated = patch.AutoGenerated
                });
            }

            lstVersions.SelectedItem = _versions.FirstOrDefault(v =>
                string.Equals(v.Id, selectedVersionId, StringComparison.OrdinalIgnoreCase));
            if (lstVersions.SelectedItem == null && _versions.Count > 0)
                lstVersions.SelectedIndex = 0;

            lstPatches.SelectedItem = _patches.FirstOrDefault(p =>
                string.Equals($"{p.From}->{p.To}", selectedPatchKey, StringComparison.OrdinalIgnoreCase));
            if (lstPatches.SelectedItem == null && _patches.Count > 0)
                lstPatches.SelectedIndex = 0;

            RefreshVersionScripts();
            RefreshPatchScripts();
            UpdateButtonsState();
        }
        finally
        {
            _isRefreshing = false;
        }
    }

    private string? GetSelectedPatchKey()
    {
        if (lstPatches.SelectedItem is not PatchDisplayItem item)
            return null;

        return $"{item.From}->{item.To}";
    }

    private async Task OnMutationCompletedAsync()
    {
        await RefreshAdminDataAsync();

        if (_onDataChanged != null)
            await _onDataChanged.Invoke();
    }

    private void LstVersions_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (_isRefreshing)
            return;

        RefreshVersionScripts();
        UpdateButtonsState();
    }

    private void LstScripts_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (_isRefreshing)
            return;

        UpdateButtonsState();
    }

    private void LstPatches_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (_isRefreshing)
            return;

        RefreshPatchScripts();
        UpdateButtonsState();
    }

    private void LstLibraryVersions_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (lstLibraryVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        _libraryScripts.Clear();
        if (_librarySnapshot == null)
            return;

        foreach (var script in _librarySnapshot.AvailableScripts
                     .Where(s => s.StartsWith($"{selected.Id}/", StringComparison.OrdinalIgnoreCase))
                     .OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            _libraryScripts.Add(script);
        }
    }

    private void LstLibraryLinks_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        UpdateButtonsState();
    }

    private async Task ScanCatalogAsync()
    {
        var folder = txtActivePatchesFolder.Text.Trim();
        _librarySnapshot = await _catalogService.ScanAsync(folder);
        RenderLibrarySnapshot(_librarySnapshot);
    }

    private void RenderLibrarySnapshot(PatchCatalogSnapshot snapshot)
    {
        _libraryVersions.Clear();
        foreach (var version in snapshot.Versions.OrderBy(v => v.Order))
        {
            _libraryVersions.Add(new VersionDisplayItem
            {
                Id = version.Id,
                Name = version.Name,
                UpgradesTo = version.UpgradesTo,
                ScriptCount = snapshot.AvailableScripts.Count(s =>
                    s.StartsWith($"{version.Id}/", StringComparison.OrdinalIgnoreCase))
            });
        }

        cmbLinkFrom.ItemsSource = snapshot.Versions.OrderBy(v => v.Order).ToList();
        cmbLinkTo.ItemsSource = snapshot.Versions.OrderBy(v => v.Order).ToList();

        var totalErrors = snapshot.Validation.Errors.Count;
        var totalWarnings = snapshot.Validation.Warnings.Count;
        txtPatchCatalogSummary.Text =
            $"Detected {snapshot.Versions.Count} version(s), {snapshot.Patches.Count} patch link(s), {snapshot.AvailableScripts.Count} script(s).";
        txtPatchCatalogValidation.Text =
            totalErrors > 0
                ? $"Validation: {totalErrors} error(s), {totalWarnings} warning(s). Fix errors before applying."
                : $"Validation: OK ({totalWarnings} warning(s)).";

        _libraryScripts.Clear();
        if (_libraryVersions.Count > 0)
            lstLibraryVersions.SelectedIndex = 0;
    }

    private void RefreshVersionScripts()
    {
        _scriptsForVersion.Clear();

        if (lstVersions.SelectedItem is not VersionDisplayItem selectedVersion)
            return;

        foreach (var script in _versionService.GetScriptsForVersion(selectedVersion.Id)
                     .OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            _scriptsForVersion.Add(script);
        }
    }

    private void RefreshPatchScripts()
    {
        _scriptsForPatch.Clear();

        if (lstPatches.SelectedItem is not PatchDisplayItem selectedPatch)
            return;

        var patch = _versionService.GetAllPatches().FirstOrDefault(p =>
            string.Equals(p.From, selectedPatch.From, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.To, selectedPatch.To, StringComparison.OrdinalIgnoreCase));

        if (patch == null)
            return;

        foreach (var script in patch.Scripts)
            _scriptsForPatch.Add(script);
    }

    private void UpdateButtonsState()
    {
        var state = _uiStateController.GetState(
            hasVersionSelection: lstVersions.SelectedItem is VersionDisplayItem,
            hasVersionScriptSelection: lstScripts.SelectedItem is string,
            hasPatchSelection: lstPatches.SelectedItem is PatchDisplayItem,
            hasStagedLinkSelection: lstLibraryLinks.SelectedItem is StagedPatchLinkDisplay,
            hasStagedChanges: _stagedLinks.Count > 0);

        btnEditVersion.IsEnabled = state.EditVersionEnabled;
        btnDeleteVersion.IsEnabled = state.DeleteVersionEnabled;
        btnAddScript.IsEnabled = state.AddScriptEnabled;
        btnRemoveScript.IsEnabled = state.RemoveScriptEnabled;

        btnEditPatch.IsEnabled = state.EditPatchEnabled;
        btnDeletePatch.IsEnabled = state.DeletePatchEnabled;
        btnRemoveStagedLink.IsEnabled = state.RemoveStagedLinkEnabled;
        btnApplyCatalog.IsEnabled = state.ApplyCatalogEnabled;
    }

    private void StageLink(string fromVersion, string toVersion, bool manual)
    {
        if (_librarySnapshot == null)
            return;

        var from = fromVersion.Trim();
        var to = toVersion.Trim();
        if (string.IsNullOrWhiteSpace(from) || string.IsNullOrWhiteSpace(to) || string.Equals(from, to, StringComparison.OrdinalIgnoreCase))
            return;

        var scripts = _librarySnapshot.AvailableScripts
            .Where(s => s.StartsWith($"{to}/", StringComparison.OrdinalIgnoreCase))
            .OrderBy(s => s, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (scripts.Count == 0)
            return;

        var existsAlready = _librarySnapshot.Patches.Any(p =>
            string.Equals(p.From, from, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.To, to, StringComparison.OrdinalIgnoreCase));
        var stagedAlready = _stagedLinkMutations.Any(m =>
            string.Equals(m.FromVersion, from, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(m.ToVersion, to, StringComparison.OrdinalIgnoreCase));

        if (existsAlready || stagedAlready)
            return;

        _stagedLinkMutations.Add(new PatchLinkMutation
        {
            Type = PatchLinkMutationType.AddOrUpdate,
            FromVersion = from,
            ToVersion = to,
            Scripts = scripts,
            Manual = manual
        });
        _stagedLinks.Add(new StagedPatchLinkDisplay
        {
            From = from,
            To = to,
            ScriptCount = scripts.Count,
            Manual = manual
        });
        UpdateButtonsState();
    }

    private async void BtnScanCatalog_Click(object sender, RoutedEventArgs e)
    {
        await ScanCatalogAsync();
    }

    private void BtnCreateMissingLinks_Click(object sender, RoutedEventArgs e)
    {
        if (_librarySnapshot == null)
            return;

        if (cmbLinkFrom.SelectedItem is VersionInfo from && cmbLinkTo.SelectedItem is VersionInfo to)
        {
            StageLink(from.Id, to.Id, manual: false);
            return;
        }

        foreach (var version in _librarySnapshot.Versions.Where(v => !string.IsNullOrWhiteSpace(v.UpgradesTo)))
        {
            StageLink(version.Id, version.UpgradesTo!, manual: false);
        }
    }

    private void BtnAddManualLink_Click(object sender, RoutedEventArgs e)
    {
        if (cmbLinkFrom.SelectedItem is not VersionInfo from || cmbLinkTo.SelectedItem is not VersionInfo to)
            return;

        StageLink(from.Id, to.Id, manual: true);
    }

    private void BtnRemoveStagedLink_Click(object sender, RoutedEventArgs e)
    {
        if (lstLibraryLinks.SelectedItem is not StagedPatchLinkDisplay selected)
            return;

        _stagedLinks.Remove(selected);
        _stagedLinkMutations.RemoveAll(m =>
            string.Equals(m.FromVersion, selected.From, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(m.ToVersion, selected.To, StringComparison.OrdinalIgnoreCase));
        UpdateButtonsState();
    }

    private async void BtnApplyCatalog_Click(object sender, RoutedEventArgs e)
    {
        if (_stagedLinkMutations.Count == 0)
            return;

        var folder = txtActivePatchesFolder.Text.Trim();
        var mutation = new PatchCatalogMutation
        {
            PatchLinks = _stagedLinkMutations.ToList()
        };

        var snapshot = await _catalogService.ApplyAsync(folder, mutation);
        if (snapshot.Validation.HasErrors)
        {
            MessageBox.Show(
                "Applied changes but validation still has errors. Review folder/scripts before running patches.",
                "Patch Library",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }

        _stagedLinkMutations.Clear();
        _stagedLinks.Clear();
        _librarySnapshot = snapshot;
        RenderLibrarySnapshot(snapshot);

        await ReloadVersionServiceFromHostAsync();
        await OnMutationCompletedAsync();
    }

    private async Task ReloadVersionServiceFromHostAsync()
    {
        var updated = _getVersionService?.Invoke();
        if (updated != null)
            _versionService = updated;

        await RefreshAdminDataAsync();
    }

    private async void BtnChangeCatalogFolder_Click(object sender, RoutedEventArgs e)
    {
        if (_setPatchesFolderAsync == null)
            return;

        var dialog = new OpenFolderDialog
        {
            Title = "Select patches folder",
            InitialDirectory = txtActivePatchesFolder.Text.Trim(),
            Multiselect = false
        };

        if (dialog.ShowDialog() != true)
            return;

        await _setPatchesFolderAsync(dialog.FolderName);
        txtActivePatchesFolder.Text = dialog.FolderName;
        await ReloadVersionServiceFromHostAsync();
        await ScanCatalogAsync();
        if (_persistSettingsAsync != null)
            await _persistSettingsAsync();
    }

    private async void BtnResetCatalogFolder_Click(object sender, RoutedEventArgs e)
    {
        if (_resetPatchesFolderAsync == null)
            return;

        var folder = await _resetPatchesFolderAsync();
        txtActivePatchesFolder.Text = folder;
        await ReloadVersionServiceFromHostAsync();
        await ScanCatalogAsync();
        if (_persistSettingsAsync != null)
            await _persistSettingsAsync();
    }

    private void BtnOpenCatalogFolder_Click(object sender, RoutedEventArgs e)
    {
        var folder = txtActivePatchesFolder.Text.Trim();
        if (!Directory.Exists(folder))
        {
            MessageBox.Show("Patches folder does not exist.", "Open Folder", MessageBoxButton.OK, MessageBoxImage.Warning);
            return;
        }

        Process.Start(new ProcessStartInfo
        {
            FileName = folder,
            UseShellExecute = true
        });
    }

    private async void BtnValidateCatalog_Click(object sender, RoutedEventArgs e)
    {
        var validation = await _catalogService.ValidateAsync(txtActivePatchesFolder.Text.Trim());
        var msg = validation.HasErrors
            ? $"Validation failed: {validation.Errors.Count} error(s), {validation.Warnings.Count} warning(s)."
            : $"Validation passed with {validation.Warnings.Count} warning(s).";
        MessageBox.Show(msg, "Patch Catalog Validation", MessageBoxButton.OK,
            validation.HasErrors ? MessageBoxImage.Warning : MessageBoxImage.Information);
    }

    private async void BtnAddVersion_Click(object sender, RoutedEventArgs e)
    {
        var dialog = new VersionEditDialog(_versionService.GetAllVersions())
        {
            Owner = this
        };

        if (dialog.ShowDialog() != true)
            return;

        await _versionService.AddVersionAsync(dialog.VersionId, dialog.VersionName, dialog.UpgradesTo);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnEditVersion_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        var current = _versionService.GetAllVersions()
            .FirstOrDefault(v => string.Equals(v.Id, selected.Id, StringComparison.OrdinalIgnoreCase));
        if (current == null)
            return;

        var dialog = new VersionEditDialog(_versionService.GetAllVersions(), current.Id, current.Name, current.UpgradesTo)
        {
            Owner = this
        };

        if (dialog.ShowDialog() != true)
            return;

        await _versionService.UpdateVersionAsync(current.Id, dialog.VersionName, dialog.UpgradesTo);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnDeleteVersion_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        var result = MessageBox.Show(
            $"Delete version '{selected.Id}' and related patches?",
            "Delete Version",
            MessageBoxButton.YesNo,
            MessageBoxImage.Warning);

        if (result != MessageBoxResult.Yes)
            return;

        await _versionService.DeleteVersionAsync(selected.Id);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnAddScript_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        var dialog = new OpenFileDialog
        {
            Title = "Select SQL Script(s)",
            Filter = "SQL Files (*.sql)|*.sql|All Files (*.*)|*.*",
            Multiselect = true
        };

        if (dialog.ShowDialog() != true)
            return;

        foreach (var file in dialog.FileNames)
            await _versionService.AddScriptToVersionAsync(selected.Id, file);

        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnRemoveScript_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selectedVersion || lstScripts.SelectedItem is not string scriptName)
            return;

        var result = MessageBox.Show(
            $"Remove script '{scriptName}' from version '{selectedVersion.Id}'?",
            "Remove Script",
            MessageBoxButton.YesNo,
            MessageBoxImage.Warning);

        if (result != MessageBoxResult.Yes)
            return;

        await _versionService.RemoveScriptFromVersionAsync(selectedVersion.Id, scriptName);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnAddPatch_Click(object sender, RoutedEventArgs e)
    {
        var dialog = new PatchEditDialog(
            _versionService.GetAllVersions(),
            _versionService.GetAvailableScripts(),
            _versionService.GetPatchesFolder())
        {
            Owner = this
        };

        if (dialog.ShowDialog() != true)
            return;

        await _versionService.AddPatchAsync(dialog.FromVersion, dialog.ToVersion);
        await _versionService.UpdatePatchScriptsAsync(dialog.FromVersion, dialog.ToVersion, dialog.Scripts);
        await _versionService.MarkPatchManualAsync(dialog.FromVersion, dialog.ToVersion);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnEditPatch_Click(object sender, RoutedEventArgs e)
    {
        if (lstPatches.SelectedItem is not PatchDisplayItem selected)
            return;

        var patch = _versionService.GetAllPatches().FirstOrDefault(p =>
            string.Equals(p.From, selected.From, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.To, selected.To, StringComparison.OrdinalIgnoreCase));
        if (patch == null)
            return;

        var dialog = new PatchEditDialog(
            _versionService.GetAllVersions(),
            _versionService.GetAvailableScripts(),
            _versionService.GetPatchesFolder(),
            patch.From,
            patch.To,
            patch.Scripts.ToList())
        {
            Owner = this
        };

        if (dialog.ShowDialog() != true)
            return;

        await _versionService.UpdatePatchAsync(patch.From, patch.To, dialog.FromVersion, dialog.ToVersion);
        await _versionService.UpdatePatchScriptsAsync(dialog.FromVersion, dialog.ToVersion, dialog.Scripts);
        await _versionService.MarkPatchManualAsync(dialog.FromVersion, dialog.ToVersion);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnDeletePatch_Click(object sender, RoutedEventArgs e)
    {
        if (lstPatches.SelectedItem is not PatchDisplayItem selected)
            return;

        var result = MessageBox.Show(
            $"Delete patch '{selected.From} -> {selected.To}'?",
            "Delete Patch",
            MessageBoxButton.YesNo,
            MessageBoxImage.Warning);

        if (result != MessageBoxResult.Yes)
            return;

        await _versionService.DeletePatchAsync(selected.From, selected.To);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }
}
