using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using MagDbPatcher.Infrastructure;
using MagDbPatcher.Models;
using MagDbPatcher.Services;
using MagDbPatcher.ViewModels;
using MagDbPatcher.Workflows;
using Microsoft.Win32;

namespace MagDbPatcher;

public partial class AdminWindow : Window
{
    private VersionService _versionService;
    private readonly Func<Task>? _onDataChanged;
    private readonly Func<string> _getCurrentPatchesFolder;
    private readonly Func<string, Task>? _setPatchesFolderAsync;
    private readonly Func<Task<string>>? _resetPatchesFolderAsync;
    private readonly Func<Task>? _persistSettingsAsync;
    private readonly Func<VersionService?>? _getVersionService;

    private readonly IAdminCatalogOrchestrator _catalogOrchestrator;
    private readonly AdminUiStateController _uiStateController = new();
    private readonly IUserDialogService _dialogs = new UserDialogService();

    private readonly ObservableCollection<VersionDisplayItem> _versions = new();
    private readonly ObservableCollection<PatchDisplayItem> _patches = new();
    private readonly ObservableCollection<string> _scriptsForVersion = new();
    private readonly ObservableCollection<VersionDisplayItem> _libraryVersions = new();
    private readonly ObservableCollection<string> _libraryScripts = new();
    private readonly ObservableCollection<StagedPatchLinkDisplay> _stagedLinks = new();

    private readonly List<PatchLinkMutation> _stagedLinkMutations = new();
    private readonly ObservableCollection<string> _editPatchScripts = new();
    private PatchCatalogSnapshot? _librarySnapshot;
    private bool _isRefreshing;
    private bool _isAddingNewVersion;
    private bool _isAddingNewPatch;

    public AdminWindow(
        VersionService versionService,
        Func<Task>? onDataChanged = null,
        Func<string>? getCurrentPatchesFolder = null,
        Func<string, Task>? setPatchesFolderAsync = null,
        Func<Task<string>>? resetPatchesFolderAsync = null,
        Func<Task>? persistSettingsAsync = null,
        Func<VersionService?>? getVersionService = null,
        IAdminCatalogOrchestrator? catalogOrchestrator = null)
    {
        _versionService = versionService;
        _onDataChanged = onDataChanged;
        _getCurrentPatchesFolder = getCurrentPatchesFolder ?? (() => versionService.GetPatchesFolder());
        _setPatchesFolderAsync = setPatchesFolderAsync;
        _resetPatchesFolderAsync = resetPatchesFolderAsync;
        _persistSettingsAsync = persistSettingsAsync;
        _getVersionService = getVersionService;
        _catalogOrchestrator = catalogOrchestrator ?? new AdminCatalogOrchestrator();

        InitializeComponent();

        lstVersions.ItemsSource = _versions;
        lstPatches.ItemsSource = _patches;
        lstScripts.ItemsSource = _scriptsForVersion;
        lstPatchScripts.ItemsSource = _editPatchScripts;
        lstLibraryVersions.ItemsSource = _libraryVersions;
        lstLibraryScripts.ItemsSource = _libraryScripts;
        lstLibraryLinks.ItemsSource = _stagedLinks;

        Loaded += AdminWindow_Loaded;
    }

    private async void AdminWindow_Loaded(object sender, RoutedEventArgs e)
    {
        txtActivePatchesFolder.Text = _getCurrentPatchesFolder();
        await RefreshAdminDataAsync();
        await ScanCatalogAsync();
    }

    public async Task RefreshAdminDataAsync()
    {
        if (_isRefreshing)
            return;

        _isRefreshing = true;
        try
        {
            await _versionService.LoadVersionsAsync();

            var allVersions = _versionService.GetAllVersions();
            var allPatches = _versionService.GetAllPatches();

            var selectedVersionId = (lstVersions.SelectedItem as VersionDisplayItem)?.Id;
            var selectedPatchKey = GetSelectedPatchKey();

            _versions.Clear();
            foreach (var version in allVersions)
            {
                _versions.Add(new VersionDisplayItem
                {
                    Id = version.Id,
                    Name = version.Name,
                    UpgradesTo = version.UpgradesTo,
                    ScriptCount = _versionService.GetScriptCount(version.Id)
                });
            }

            _patches.Clear();
            foreach (var patch in allPatches
                         .OrderBy(p => p.From, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(p => p.To, StringComparer.OrdinalIgnoreCase))
            {
                _patches.Add(new PatchDisplayItem
                {
                    From = patch.From,
                    To = patch.To,
                    ScriptCount = patch.Scripts.Count,
                    IsAutoGenerated = patch.AutoGenerated
                });
            }

            lstVersions.SelectedItem = _versions.FirstOrDefault(v =>
                string.Equals(v.Id, selectedVersionId, StringComparison.OrdinalIgnoreCase));
            if (lstVersions.SelectedItem == null && _versions.Count > 0)
                lstVersions.SelectedIndex = 0;

            lstPatches.SelectedItem = _patches.FirstOrDefault(p =>
                string.Equals($"{p.From}->{p.To}", selectedPatchKey, StringComparison.OrdinalIgnoreCase));
            if (lstPatches.SelectedItem == null && _patches.Count > 0)
                lstPatches.SelectedIndex = 0;

            RefreshVersionScripts();
            RefreshPatchScripts();
            UpdateButtonsState();
            RebuildChainVisualization();
        }
        finally
        {
            _isRefreshing = false;
        }
    }

    private void RebuildChainVisualization()
    {
        var versions = _versionService.GetAllVersions();
        if (versions.Count == 0)
        {
            txtVersionChain.Text = "(no versions)";
            return;
        }

        var parts = new System.Text.StringBuilder();
        foreach (var v in versions)
        {
            if (parts.Length > 0)
                parts.Append("  →  ");
            parts.Append(v.Id);
        }
        txtVersionChain.Text = parts.ToString();
    }

    private string? GetSelectedPatchKey()
    {
        if (lstPatches.SelectedItem is not PatchDisplayItem item)
            return null;

        return $"{item.From}->{item.To}";
    }

    private async Task OnMutationCompletedAsync()
    {
        await RefreshAdminDataAsync();

        if (_onDataChanged != null)
            await _onDataChanged.Invoke();
    }

    private void LstVersions_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (_isRefreshing)
            return;

        RefreshVersionScripts();
        UpdateButtonsState();
        PopulateVersionForm(lstVersions.SelectedItem as VersionDisplayItem);
    }

    private void PopulateVersionForm(VersionDisplayItem? item)
    {
        _isAddingNewVersion = false;
        bdVersionValidation.Visibility = System.Windows.Visibility.Collapsed;
        pnlVersionPredecessor.Visibility = System.Windows.Visibility.Collapsed;

        if (item == null)
        {
            txtVersionFormHeader.Text = "Select a version to edit";
            txtEditVersionId.Text = "";
            txtEditVersionId.IsEnabled = false;
            txtEditVersionName.Text = "";
            txtEditVersionName.IsEnabled = false;
            cmbEditUpgradesTo.IsEnabled = false;
            btnSaveVersion.IsEnabled = false;
            btnDiscardVersion.IsEnabled = false;
            return;
        }

        txtVersionFormHeader.Text = $"Editing: {item.Id}";
        txtEditVersionId.Text = item.Id;
        txtEditVersionId.IsEnabled = false;
        txtEditVersionName.Text = item.Name;
        txtEditVersionName.IsEnabled = true;

        var allVersions = _versionService.GetAllVersions();
        var otherVersions = allVersions
            .Where(v => !string.Equals(v.Id, item.Id, StringComparison.OrdinalIgnoreCase))
            .ToList();
        cmbEditUpgradesTo.ItemsSource = otherVersions;
        cmbEditUpgradesTo.SelectedItem = otherVersions.FirstOrDefault(v =>
            string.Equals(v.Id, item.UpgradesTo, StringComparison.OrdinalIgnoreCase));
        cmbEditUpgradesTo.IsEnabled = true;

        btnSaveVersion.IsEnabled = true;
        btnDiscardVersion.IsEnabled = true;
    }

    private void LstScripts_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (_isRefreshing)
            return;

        UpdateButtonsState();
    }

    private void LstPatches_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (_isRefreshing)
            return;

        RefreshPatchScripts();
        UpdateButtonsState();
        PopulatePatchForm(lstPatches.SelectedItem as PatchDisplayItem);
    }

    private void PopulatePatchForm(PatchDisplayItem? item)
    {
        _isAddingNewPatch = false;
        bdPatchValidation.Visibility = System.Windows.Visibility.Collapsed;

        var allVersions = _versionService.GetAllVersions();
        cmbEditPatchFrom.ItemsSource = allVersions;
        cmbEditPatchTo.ItemsSource = allVersions;

        if (item == null)
        {
            txtPatchFormHeader.Text = "Select a patch to edit";
            cmbEditPatchFrom.SelectedItem = null;
            cmbEditPatchTo.SelectedItem = null;
            cmbEditPatchFrom.IsEnabled = false;
            cmbEditPatchTo.IsEnabled = false;
            _editPatchScripts.Clear();
            SetPatchFormEnabled(false);
            return;
        }

        txtPatchFormHeader.Text = $"Editing: {item.From}  →  {item.To}";
        cmbEditPatchFrom.SelectedItem = allVersions.FirstOrDefault(v =>
            string.Equals(v.Id, item.From, StringComparison.OrdinalIgnoreCase));
        cmbEditPatchTo.SelectedItem = allVersions.FirstOrDefault(v =>
            string.Equals(v.Id, item.To, StringComparison.OrdinalIgnoreCase));

        // Auto-generated patches: lock From/To since auto-gen will overwrite them
        cmbEditPatchFrom.IsEnabled = !item.IsAutoGenerated;
        cmbEditPatchTo.IsEnabled = !item.IsAutoGenerated;

        _editPatchScripts.Clear();
        var patch = _versionService.GetAllPatches().FirstOrDefault(p =>
            string.Equals(p.From, item.From, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.To, item.To, StringComparison.OrdinalIgnoreCase));
        if (patch != null)
            foreach (var s in patch.Scripts)
                _editPatchScripts.Add(s);

        SetPatchFormEnabled(true);
    }

    private void SetPatchFormEnabled(bool enabled)
    {
        btnSavePatch.IsEnabled = enabled;
        btnDiscardPatch.IsEnabled = enabled;
        btnAddEditScript.IsEnabled = enabled;
        btnAutoFillScripts.IsEnabled = enabled;
        lstPatchScripts.IsEnabled = enabled;
        UpdatePatchScriptActionButtons();
    }

    private void UpdatePatchScriptActionButtons()
    {
        var hasSelection = lstPatchScripts.SelectedItem is string;
        var idx = lstPatchScripts.SelectedIndex;
        btnRemoveEditScript.IsEnabled = hasSelection && lstPatchScripts.IsEnabled;
        btnMoveScriptUp.IsEnabled = hasSelection && idx > 0 && lstPatchScripts.IsEnabled;
        btnMoveScriptDown.IsEnabled = hasSelection && idx < _editPatchScripts.Count - 1 && lstPatchScripts.IsEnabled;
    }

    private void LstLibraryVersions_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (lstLibraryVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        _libraryScripts.Clear();
        if (_librarySnapshot == null)
            return;

        foreach (var script in _librarySnapshot.AvailableScripts
                     .Where(s => s.StartsWith($"{selected.Id}/", StringComparison.OrdinalIgnoreCase))
                     .OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            _libraryScripts.Add(script);
        }
    }

    private void LstLibraryLinks_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        UpdateButtonsState();
    }

    private async Task ScanCatalogAsync()
    {
        var folder = txtActivePatchesFolder.Text.Trim();
        _librarySnapshot = await _catalogOrchestrator.ScanAsync(folder);
        RenderLibrarySnapshot(_librarySnapshot);
    }

    private void RenderLibrarySnapshot(PatchCatalogSnapshot snapshot)
    {
        _libraryVersions.Clear();
        foreach (var version in snapshot.Versions.OrderBy(v => v.Order))
        {
            _libraryVersions.Add(new VersionDisplayItem
            {
                Id = version.Id,
                Name = version.Name,
                UpgradesTo = version.UpgradesTo,
                ScriptCount = snapshot.AvailableScripts.Count(s =>
                    s.StartsWith($"{version.Id}/", StringComparison.OrdinalIgnoreCase))
            });
        }

        var orderedVersions = snapshot.Versions.OrderBy(v => v.Order).ToList();
        cmbLinkFrom.ItemsSource = orderedVersions;
        cmbLinkTo.ItemsSource = orderedVersions;
        if (orderedVersions.Count > 0)
        {
            cmbLinkFrom.SelectedIndex = 0;
            cmbLinkTo.SelectedIndex = orderedVersions.Count - 1;
        }

        var totalErrors = snapshot.Validation.Errors.Count;
        var totalWarnings = snapshot.Validation.Warnings.Count;
        var summary = $"Detected {snapshot.Versions.Count} version(s), {snapshot.Patches.Count} patch link(s), {snapshot.AvailableScripts.Count} script(s).";
        var validationMsg = totalErrors > 0
            ? $"{totalErrors} error(s), {totalWarnings} warning(s) — fix errors before applying."
            : totalWarnings > 0
                ? $"OK with {totalWarnings} warning(s)."
                : "All checks passed.";

        var bannerStyle = totalErrors > 0 ? "StatusBannerError"
            : totalWarnings > 0 ? "StatusBannerWarning"
            : "StatusBannerSuccess";

        bdCatalogStatus.Style = FindResource(bannerStyle) as Style;
        txtCatalogStatusMsg.Text = $"{summary} {validationMsg}";
        bdCatalogStatus.Visibility = System.Windows.Visibility.Visible;

        txtFolderStatus.Text = $"Contains {snapshot.Versions.Count} version(s), {snapshot.AvailableScripts.Count} script(s)";

        _libraryScripts.Clear();
        if (_libraryVersions.Count > 0)
            lstLibraryVersions.SelectedIndex = 0;
    }

    private void RefreshVersionScripts()
    {
        _scriptsForVersion.Clear();

        if (lstVersions.SelectedItem is not VersionDisplayItem selectedVersion)
            return;

        foreach (var script in _versionService.GetScriptsForVersion(selectedVersion.Id)
                     .OrderBy(s => s, StringComparer.OrdinalIgnoreCase))
        {
            _scriptsForVersion.Add(script);
        }
    }

    private void RefreshPatchScripts()
    {
        _editPatchScripts.Clear();

        if (lstPatches.SelectedItem is not PatchDisplayItem selectedPatch)
            return;

        var patch = _versionService.GetAllPatches().FirstOrDefault(p =>
            string.Equals(p.From, selectedPatch.From, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.To, selectedPatch.To, StringComparison.OrdinalIgnoreCase));

        if (patch == null)
            return;

        foreach (var script in patch.Scripts)
            _editPatchScripts.Add(script);
    }

    private void UpdateButtonsState()
    {
        var state = _uiStateController.GetState(
            hasVersionSelection: lstVersions.SelectedItem is VersionDisplayItem,
            hasVersionScriptSelection: lstScripts.SelectedItem is string,
            hasPatchSelection: lstPatches.SelectedItem is PatchDisplayItem,
            hasStagedLinkSelection: lstLibraryLinks.SelectedItem is StagedPatchLinkDisplay,
            hasStagedChanges: _stagedLinks.Count > 0);

        btnDeleteVersion.IsEnabled = state.DeleteVersionEnabled;
        btnOpenVersionFolder.IsEnabled = state.AddScriptEnabled;
        btnAddScript.IsEnabled = state.AddScriptEnabled;
        btnRemoveScript.IsEnabled = state.RemoveScriptEnabled;

        btnDeletePatch.IsEnabled = state.DeletePatchEnabled;
        btnRemoveStagedLink.IsEnabled = state.RemoveStagedLinkEnabled;
        btnApplyCatalog.IsEnabled = state.ApplyCatalogEnabled;
    }

    private void StageLink(string fromVersion, string toVersion, bool manual)
    {
        if (_librarySnapshot == null)
            return;

        var from = fromVersion.Trim();
        var to = toVersion.Trim();
        if (string.IsNullOrWhiteSpace(from) || string.IsNullOrWhiteSpace(to) || string.Equals(from, to, StringComparison.OrdinalIgnoreCase))
            return;

        var scripts = _librarySnapshot.AvailableScripts
            .Where(s => s.StartsWith($"{to}/", StringComparison.OrdinalIgnoreCase))
            .OrderBy(s => s, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (scripts.Count == 0)
            return;

        var existsAlready = _librarySnapshot.Patches.Any(p =>
            string.Equals(p.From, from, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.To, to, StringComparison.OrdinalIgnoreCase));
        var stagedAlready = _stagedLinkMutations.Any(m =>
            string.Equals(m.FromVersion, from, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(m.ToVersion, to, StringComparison.OrdinalIgnoreCase));

        if (existsAlready || stagedAlready)
            return;

        _stagedLinkMutations.Add(new PatchLinkMutation
        {
            Type = PatchLinkMutationType.AddOrUpdate,
            FromVersion = from,
            ToVersion = to,
            Scripts = scripts,
            Manual = manual
        });
        _stagedLinks.Add(new StagedPatchLinkDisplay
        {
            From = from,
            To = to,
            ScriptCount = scripts.Count,
            Manual = manual
        });
        UpdateButtonsState();
    }

    private async void BtnScanCatalog_Click(object sender, RoutedEventArgs e)
    {
        await ScanCatalogAsync();
    }

    private void BtnCreateMissingLinks_Click(object sender, RoutedEventArgs e)
    {
        if (_librarySnapshot == null)
            return;

        if (cmbLinkFrom.SelectedItem is VersionInfo from && cmbLinkTo.SelectedItem is VersionInfo to)
        {
            StageLink(from.Id, to.Id, manual: false);
            return;
        }

        foreach (var version in _librarySnapshot.Versions.Where(v => !string.IsNullOrWhiteSpace(v.UpgradesTo)))
        {
            StageLink(version.Id, version.UpgradesTo!, manual: false);
        }
    }

    private void BtnAddManualLink_Click(object sender, RoutedEventArgs e)
    {
        if (cmbLinkFrom.SelectedItem is not VersionInfo from || cmbLinkTo.SelectedItem is not VersionInfo to)
            return;

        StageLink(from.Id, to.Id, manual: true);
    }

    private void BtnRemoveStagedLink_Click(object sender, RoutedEventArgs e)
    {
        if (lstLibraryLinks.SelectedItem is not StagedPatchLinkDisplay selected)
            return;

        _stagedLinks.Remove(selected);
        _stagedLinkMutations.RemoveAll(m =>
            string.Equals(m.FromVersion, selected.From, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(m.ToVersion, selected.To, StringComparison.OrdinalIgnoreCase));
        UpdateButtonsState();
    }

    private async void BtnApplyCatalog_Click(object sender, RoutedEventArgs e)
    {
        if (_stagedLinkMutations.Count == 0)
            return;

        var folder = txtActivePatchesFolder.Text.Trim();
        var mutation = new PatchCatalogMutation
        {
            PatchLinks = _stagedLinkMutations.ToList()
        };

        var snapshot = await _catalogOrchestrator.ApplyAsync(folder, mutation);
        if (snapshot.Validation.HasErrors)
        {
            _dialogs.ShowWarning(
                "Applied changes but validation still has errors. Review folder/scripts before running patches.",
                "Patch Library");
        }

        _stagedLinkMutations.Clear();
        _stagedLinks.Clear();
        _librarySnapshot = snapshot;
        RenderLibrarySnapshot(snapshot);

        await ReloadVersionServiceFromHostAsync();
        await OnMutationCompletedAsync();
    }

    private async Task ReloadVersionServiceFromHostAsync()
    {
        var updated = _getVersionService?.Invoke();
        if (updated != null)
            _versionService = updated;

        await RefreshAdminDataAsync();
    }

    private async void BtnChangeCatalogFolder_Click(object sender, RoutedEventArgs e)
    {
        if (_setPatchesFolderAsync == null)
            return;

        var dialog = new OpenFolderDialog
        {
            Title = "Select patches folder",
            InitialDirectory = txtActivePatchesFolder.Text.Trim(),
            Multiselect = false
        };

        if (dialog.ShowDialog() != true)
            return;

        await _setPatchesFolderAsync(dialog.FolderName);
        txtActivePatchesFolder.Text = dialog.FolderName;
        await ReloadVersionServiceFromHostAsync();
        await ScanCatalogAsync();
        if (_persistSettingsAsync != null)
            await _persistSettingsAsync();
    }

    private async void BtnResetCatalogFolder_Click(object sender, RoutedEventArgs e)
    {
        if (_resetPatchesFolderAsync == null)
            return;

        var folder = await _resetPatchesFolderAsync();
        txtActivePatchesFolder.Text = folder;
        await ReloadVersionServiceFromHostAsync();
        await ScanCatalogAsync();
        if (_persistSettingsAsync != null)
            await _persistSettingsAsync();
    }

    private void BtnOpenCatalogFolder_Click(object sender, RoutedEventArgs e)
    {
        var folder = txtActivePatchesFolder.Text.Trim();
        if (!Directory.Exists(folder))
        {
            _dialogs.ShowWarning("Patches folder does not exist.", "Open Folder");
            return;
        }

        Process.Start(new ProcessStartInfo
        {
            FileName = folder,
            UseShellExecute = true
        });
    }

    private async void BtnValidateCatalog_Click(object sender, RoutedEventArgs e)
    {
        var validation = await _catalogOrchestrator.ValidateAsync(txtActivePatchesFolder.Text.Trim());
        var bannerStyle = validation.HasErrors ? "StatusBannerError"
            : validation.Warnings.Count > 0 ? "StatusBannerWarning"
            : "StatusBannerSuccess";
        var msg = validation.HasErrors
            ? $"Validation failed: {validation.Errors.Count} error(s), {validation.Warnings.Count} warning(s)."
            : $"Validation passed with {validation.Warnings.Count} warning(s).";
        bdCatalogStatus.Style = FindResource(bannerStyle) as Style;
        txtCatalogStatusMsg.Text = msg;
        bdCatalogStatus.Visibility = System.Windows.Visibility.Visible;
    }

    private void BtnAddVersion_Click(object sender, RoutedEventArgs e)
    {
        _isAddingNewVersion = true;
        lstVersions.UnselectAll();
        txtVersionFormHeader.Text = "Add New Version";
        txtEditVersionId.Text = "";
        txtEditVersionId.IsEnabled = true;
        txtEditVersionName.Text = "";
        txtEditVersionName.IsEnabled = true;

        var allVersions = _versionService.GetAllVersions();
        cmbEditUpgradesTo.ItemsSource = allVersions;
        cmbEditUpgradesTo.SelectedItem = null;
        cmbEditUpgradesTo.IsEnabled = true;

        // Show "Connects after" field and pre-select the current chain tail
        var chainTail = allVersions
            .Where(v => string.IsNullOrWhiteSpace(v.UpgradesTo))
            .MaxBy(v => v.Order);
        cmbVersionPredecessor.ItemsSource = allVersions;
        cmbVersionPredecessor.SelectedItem = chainTail;
        pnlVersionPredecessor.Visibility = System.Windows.Visibility.Visible;

        bdVersionValidation.Visibility = System.Windows.Visibility.Collapsed;
        btnSaveVersion.IsEnabled = false;
        btnDiscardVersion.IsEnabled = true;
        txtEditVersionId.Focus();
    }

    private void TxtEditVersionId_TextChanged(object sender, System.Windows.Controls.TextChangedEventArgs e)
    {
        if (!_isAddingNewVersion)
            return;

        var id = txtEditVersionId.Text.Trim();
        var isDuplicate = _versions.Any(v =>
            string.Equals(v.Id, id, StringComparison.OrdinalIgnoreCase));

        if (isDuplicate)
        {
            bdVersionValidation.Visibility = System.Windows.Visibility.Visible;
            txtVersionValidationMsg.Text = $"Version '{id}' already exists.";
            btnSaveVersion.IsEnabled = false;
        }
        else
        {
            bdVersionValidation.Visibility = System.Windows.Visibility.Collapsed;
            btnSaveVersion.IsEnabled = !string.IsNullOrWhiteSpace(id);
        }
    }

    private void CmbEditUpgradesTo_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        // No action needed — selection is read at save time
    }

    private async void BtnSaveVersion_Click(object sender, RoutedEventArgs e)
    {
        var id = txtEditVersionId.Text.Trim();
        var name = txtEditVersionName.Text.Trim();
        var upgradesTo = (cmbEditUpgradesTo.SelectedItem as Models.VersionInfo)?.Id;

        if (string.IsNullOrWhiteSpace(id))
        {
            bdVersionValidation.Visibility = System.Windows.Visibility.Visible;
            txtVersionValidationMsg.Text = "Version ID is required.";
            return;
        }

        if (_isAddingNewVersion)
        {
            await _versionService.AddVersionAsync(id, string.IsNullOrWhiteSpace(name) ? id : name, upgradesTo);

            // Link the predecessor's UpgradesTo → new version
            if (cmbVersionPredecessor.SelectedItem is Models.VersionInfo predecessor &&
                !string.Equals(predecessor.Id, id, StringComparison.OrdinalIgnoreCase))
            {
                await _versionService.UpdateVersionAsync(predecessor.Id, predecessor.Name, upgradesTo: id);
            }
        }
        else
        {
            var selectedId = (lstVersions.SelectedItem as VersionDisplayItem)?.Id;
            if (selectedId == null)
                return;
            await _versionService.UpdateVersionAsync(selectedId, string.IsNullOrWhiteSpace(name) ? selectedId : name, upgradesTo);
        }

        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private void BtnDiscardVersion_Click(object sender, RoutedEventArgs e)
    {
        PopulateVersionForm(lstVersions.SelectedItem as VersionDisplayItem);
    }

    private async void BtnDeleteVersion_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        if (!_dialogs.Confirm(
                $"Delete version '{selected.Id}' and related patches?",
                "Delete Version",
                useYesNo: true))
            return;

        await _versionService.DeleteVersionAsync(selected.Id);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private void BtnOpenVersionFolder_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        var folder = Path.Combine(_versionService.GetPatchesFolder(), selected.Id);
        if (!Directory.Exists(folder))
            Directory.CreateDirectory(folder);

        Process.Start(new ProcessStartInfo
        {
            FileName = folder,
            UseShellExecute = true
        });
    }

    private async void BtnAddScript_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selected)
            return;

        var dialog = new OpenFileDialog
        {
            Title = "Select SQL Script(s)",
            Filter = "SQL Files (*.sql)|*.sql|All Files (*.*)|*.*",
            Multiselect = true
        };

        if (dialog.ShowDialog() != true)
            return;

        foreach (var file in dialog.FileNames)
            await _versionService.AddScriptToVersionAsync(selected.Id, file);

        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private async void BtnRemoveScript_Click(object sender, RoutedEventArgs e)
    {
        if (lstVersions.SelectedItem is not VersionDisplayItem selectedVersion || lstScripts.SelectedItem is not string scriptName)
            return;

        if (!_dialogs.Confirm(
                $"Remove script '{scriptName}' from version '{selectedVersion.Id}'?",
                "Remove Script",
                useYesNo: true))
            return;

        await _versionService.RemoveScriptFromVersionAsync(selectedVersion.Id, scriptName);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private void BtnAddPatch_Click(object sender, RoutedEventArgs e)
    {
        _isAddingNewPatch = true;
        lstPatches.UnselectAll();
        txtPatchFormHeader.Text = "Add New Patch";

        var allVersions = _versionService.GetAllVersions();
        cmbEditPatchFrom.ItemsSource = allVersions;
        cmbEditPatchTo.ItemsSource = allVersions;
        cmbEditPatchFrom.SelectedItem = null;
        cmbEditPatchTo.SelectedItem = null;
        cmbEditPatchFrom.IsEnabled = true;
        cmbEditPatchTo.IsEnabled = true;

        _editPatchScripts.Clear();
        bdPatchValidation.Visibility = System.Windows.Visibility.Collapsed;
        SetPatchFormEnabled(true);
    }

    private void LstPatchScripts_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        UpdatePatchScriptActionButtons();
    }

    private void BtnAddEditScript_Click(object sender, RoutedEventArgs e)
    {
        var dialog = new OpenFileDialog
        {
            Title = "Select SQL Script(s)",
            Filter = "SQL Files (*.sql)|*.sql|All Files (*.*)|*.*",
            Multiselect = true,
            InitialDirectory = _versionService.GetPatchesFolder()
        };

        if (dialog.ShowDialog() != true)
            return;

        var patchesFolder = _versionService.GetPatchesFolder();
        foreach (var file in dialog.FileNames)
        {
            // Use relative path if file is inside the patches folder
            var relativeName = file.StartsWith(patchesFolder, StringComparison.OrdinalIgnoreCase)
                ? file.Substring(patchesFolder.Length).TrimStart('/', '\\').Replace('\\', '/')
                : Path.GetFileName(file);
            if (!_editPatchScripts.Contains(relativeName))
                _editPatchScripts.Add(relativeName);
        }
    }

    private void BtnRemoveEditScript_Click(object sender, RoutedEventArgs e)
    {
        if (lstPatchScripts.SelectedItem is string script)
            _editPatchScripts.Remove(script);
        UpdatePatchScriptActionButtons();
    }

    private void BtnMoveScriptUp_Click(object sender, RoutedEventArgs e)
    {
        var idx = lstPatchScripts.SelectedIndex;
        if (idx <= 0)
            return;
        _editPatchScripts.Move(idx, idx - 1);
        lstPatchScripts.SelectedIndex = idx - 1;
        UpdatePatchScriptActionButtons();
    }

    private void BtnMoveScriptDown_Click(object sender, RoutedEventArgs e)
    {
        var idx = lstPatchScripts.SelectedIndex;
        if (idx < 0 || idx >= _editPatchScripts.Count - 1)
            return;
        _editPatchScripts.Move(idx, idx + 1);
        lstPatchScripts.SelectedIndex = idx + 1;
        UpdatePatchScriptActionButtons();
    }

    private void BtnAutoFillScripts_Click(object sender, RoutedEventArgs e)
    {
        var toVersionId = (cmbEditPatchTo.SelectedItem as Models.VersionInfo)?.Id;
        if (string.IsNullOrWhiteSpace(toVersionId))
            return;

        var scripts = _versionService.GetScriptsForVersion(toVersionId)
            .Select(name => $"{toVersionId}/{name}")
            .OrderBy(s => s, StringComparer.OrdinalIgnoreCase)
            .ToList();

        _editPatchScripts.Clear();
        foreach (var s in scripts)
            _editPatchScripts.Add(s);
    }

    private async void BtnSavePatch_Click(object sender, RoutedEventArgs e)
    {
        var from = (cmbEditPatchFrom.SelectedItem as Models.VersionInfo)?.Id;
        var to = (cmbEditPatchTo.SelectedItem as Models.VersionInfo)?.Id;

        if (string.IsNullOrWhiteSpace(from) || string.IsNullOrWhiteSpace(to))
        {
            bdPatchValidation.Visibility = System.Windows.Visibility.Visible;
            txtPatchValidationMsg.Text = "Both From and To versions are required.";
            return;
        }

        if (string.Equals(from, to, StringComparison.OrdinalIgnoreCase))
        {
            bdPatchValidation.Visibility = System.Windows.Visibility.Visible;
            txtPatchValidationMsg.Text = "From and To versions must be different.";
            return;
        }

        bdPatchValidation.Visibility = System.Windows.Visibility.Collapsed;
        var scripts = _editPatchScripts.ToList();

        if (_isAddingNewPatch)
        {
            await _versionService.AddPatchAsync(from, to);
            await _versionService.UpdatePatchScriptsAsync(from, to, scripts);
            await _versionService.MarkPatchManualAsync(from, to);
        }
        else
        {
            var selected = lstPatches.SelectedItem as PatchDisplayItem;
            if (selected == null)
                return;
            await _versionService.UpdatePatchAsync(selected.From, selected.To, from, to);
            await _versionService.UpdatePatchScriptsAsync(from, to, scripts);
            if (!selected.IsAutoGenerated)
                await _versionService.MarkPatchManualAsync(from, to);
        }

        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }

    private void BtnDiscardPatch_Click(object sender, RoutedEventArgs e)
    {
        PopulatePatchForm(lstPatches.SelectedItem as PatchDisplayItem);
    }

    private async void BtnDeletePatch_Click(object sender, RoutedEventArgs e)
    {
        if (lstPatches.SelectedItem is not PatchDisplayItem selected)
            return;

        if (!_dialogs.Confirm(
                $"Delete patch '{selected.From} -> {selected.To}'?",
                "Delete Patch",
                useYesNo: true))
            return;

        await _versionService.DeletePatchAsync(selected.From, selected.To);
        await OnMutationCompletedAsync();
        await ScanCatalogAsync();
    }
}
