using System.IO;
using MagDbPatcher.Models;

namespace MagDbPatcher.Services;

internal sealed class PatchAutoGenerationService
{
    public List<string> GetScriptsInFolder(string patchesFolder, string versionId)
    {
        var versionFolder = Path.Combine(patchesFolder, versionId);
        if (!Directory.Exists(versionFolder)) return new List<string>();

        return Directory.GetFiles(versionFolder, "*.sql")
            .Select(f => $"{versionId}/{Path.GetFileName(f)}")
            .OrderBy(s => s, StringComparer.OrdinalIgnoreCase)
            .Select(path => path.Trim().Replace('\\', '/'))
            .ToList();
    }

    public bool EnsureAutoPatch(
        List<PatchInfo> patches,
        string from,
        string to,
        Dictionary<string, List<string>> scriptsByVersion,
        HashSet<string> desiredKeys)
    {
        from = from.Trim();
        to = to.Trim();

        if (!scriptsByVersion.TryGetValue(to, out var scripts) || scripts.Count == 0)
            return false;

        desiredKeys.Add(Key(from, to));

        var patch = patches.FirstOrDefault(p =>
            string.Equals(p.From.Trim(), from, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.To.Trim(), to, StringComparison.OrdinalIgnoreCase));

        if (patch == null)
        {
            patches.Add(new PatchInfo
            {
                From = from,
                To = to,
                Scripts = scripts,
                AutoGenerated = true
            });
            return true;
        }

        if (patch.AutoGenerated && !patch.Scripts.SequenceEqual(scripts))
        {
            patch.Scripts = scripts;
            return true;
        }

        return false;
    }

    public static bool IsBuildVersion(string id, string buildPattern) =>
        !string.IsNullOrWhiteSpace(id) &&
        !string.IsNullOrWhiteSpace(buildPattern) &&
        id.Contains(buildPattern, StringComparison.OrdinalIgnoreCase);

    public static int? GetMajorVersion(string id)
    {
        if (string.IsNullOrWhiteSpace(id)) return null;
        var part = id.Split('.', '-', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
        if (int.TryParse(part, out var major)) return major;
        return null;
    }
    public static string Key(string from, string to) => $"{from}->{to}";
}

