using System.IO;
using MagDbPatcher.Models;

namespace MagDbPatcher.Services;

internal sealed class PatchCatalogMutator
{
    private readonly VersionConfigRepository _repository = new();

    public async Task ApplyAsync(string rootPath, PatchCatalogMutation mutation)
    {
        var normalizedRoot = Path.GetFullPath(rootPath.Trim());
        var configPath = Path.Combine(normalizedRoot, "versions.json");
        Directory.CreateDirectory(normalizedRoot);

        var config = await _repository.LoadAsync(configPath);

        ApplyVersionMutations(config, mutation.Versions, normalizedRoot);
        ApplyPatchMutations(config, mutation.PatchLinks);
        NormalizePatchScripts(config);

        await _repository.SaveAsync(configPath, config);
    }

    private static void ApplyVersionMutations(VersionConfig config, IEnumerable<VersionMutation> mutations, string rootPath)
    {
        foreach (var mutation in mutations)
        {
            var id = NormalizeVersionId(mutation.VersionId);
            if (string.IsNullOrWhiteSpace(id))
                continue;

            if (mutation.Type == VersionMutationType.Delete)
            {
                config.Versions.RemoveAll(v => string.Equals(NormalizeVersionId(v.Id), id, StringComparison.OrdinalIgnoreCase));
                config.Patches.RemoveAll(p =>
                    string.Equals(NormalizeVersionId(p.From), id, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(NormalizeVersionId(p.To), id, StringComparison.OrdinalIgnoreCase));

                foreach (var version in config.Versions.Where(v =>
                             string.Equals(NormalizeVersionId(v.UpgradesTo ?? string.Empty), id, StringComparison.OrdinalIgnoreCase)))
                {
                    version.UpgradesTo = null;
                }

                continue;
            }

            var existing = config.Versions.FirstOrDefault(v =>
                string.Equals(NormalizeVersionId(v.Id), id, StringComparison.OrdinalIgnoreCase));

            if (existing == null)
            {
                var nextOrder = config.Versions.Any() ? config.Versions.Max(v => v.Order) + 1 : 1;
                config.Versions.Add(new VersionInfo
                {
                    Id = id,
                    Name = string.IsNullOrWhiteSpace(mutation.Name) ? id : mutation.Name.Trim(),
                    UpgradesTo = string.IsNullOrWhiteSpace(mutation.UpgradesTo) ? null : NormalizeVersionId(mutation.UpgradesTo),
                    Order = mutation.Order ?? nextOrder
                });
            }
            else
            {
                existing.Name = string.IsNullOrWhiteSpace(mutation.Name) ? existing.Name : mutation.Name.Trim();
                existing.UpgradesTo = string.IsNullOrWhiteSpace(mutation.UpgradesTo) ? null : NormalizeVersionId(mutation.UpgradesTo);
                if (mutation.Order.HasValue)
                    existing.Order = mutation.Order.Value;
            }

            Directory.CreateDirectory(Path.Combine(rootPath, id));
        }
    }

    private static void ApplyPatchMutations(VersionConfig config, IEnumerable<PatchLinkMutation> mutations)
    {
        foreach (var mutation in mutations)
        {
            var from = NormalizeVersionId(mutation.FromVersion);
            var to = NormalizeVersionId(mutation.ToVersion);
            if (string.IsNullOrWhiteSpace(from) || string.IsNullOrWhiteSpace(to))
                continue;

            if (mutation.Type == PatchLinkMutationType.Delete)
            {
                config.Patches.RemoveAll(p =>
                    string.Equals(NormalizeVersionId(p.From), from, StringComparison.OrdinalIgnoreCase) &&
                    string.Equals(NormalizeVersionId(p.To), to, StringComparison.OrdinalIgnoreCase));
                continue;
            }

            var scripts = mutation.Scripts
                .Select(NormalizeScriptPath)
                .Where(s => !string.IsNullOrWhiteSpace(s))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            var patch = config.Patches.FirstOrDefault(p =>
                string.Equals(NormalizeVersionId(p.From), from, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(NormalizeVersionId(p.To), to, StringComparison.OrdinalIgnoreCase));

            if (patch == null)
            {
                patch = new PatchInfo
                {
                    From = from,
                    To = to,
                    Scripts = scripts
                };
                config.Patches.Add(patch);
            }
            else
            {
                patch.Scripts = scripts;
            }

            patch.AutoGenerated = !mutation.Manual;
        }
    }

    private static void NormalizePatchScripts(VersionConfig config)
    {
        foreach (var patch in config.Patches)
        {
            patch.From = NormalizeVersionId(patch.From);
            patch.To = NormalizeVersionId(patch.To);
            patch.Scripts = patch.Scripts
                .Select(NormalizeScriptPath)
                .Where(s => !string.IsNullOrWhiteSpace(s))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }
    }

    private static string NormalizeVersionId(string value) => (value ?? string.Empty).Trim();

    private static string NormalizeScriptPath(string value) => (value ?? string.Empty).Trim().Replace('\\', '/');
}
