using System.Text.Json.Serialization;

namespace MagDbPatcher.Models;

public class VersionInfo
{
    public string Id { get; set; } = "";
    public string Name { get; set; } = "";
    public string? UpgradesTo { get; set; }
    public int Order { get; set; } = 0;
}

public class PatchInfo
{
    public string From { get; set; } = "";
    public string To { get; set; } = "";
    public List<string> Scripts { get; set; } = new();
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool AutoGenerated { get; set; } = false;
}

public class VersionConfig
{
    public List<VersionInfo> Versions { get; set; } = new();
    public List<PatchInfo> Patches { get; set; } = new();
}

public class PatchStep
{
    public string FromVersion { get; set; } = "";
    public string ToVersion { get; set; } = "";
    public List<string> Scripts { get; set; } = new();
}
